services:
  # 後端 API 服務
  - type: web
    name: mes-system-api
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: mes-system-db
          property: connectionString
      - key: JwtSettings__SecretKey
        generateValue: true
      - key: JwtSettings__Issuer
        value: MESSystem
      - key: JwtSettings__Audience
        value: MESSystemUsers
      - key: JwtSettings__ExpirationHours
        value: 8

  # 前端靜態網站
  - type: web
    name: mes-system-frontend
    env: static
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: ./frontend/build
    plan: free
    region: singapore
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://mes-system-api.onrender.com/api

# PostgreSQL 資料庫
databases:
  - name: mes-system-db
    databaseName: mes_system
    user: mes_user
    plan: free 